version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    restart: always
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - pixo_test


  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./var/postgres:/var/lib/postgresql/data/
    networks:
      - pixo_test

volumes:
  pixo_test:

networks:
  pixo_test: