FROM python:3.12-slim

ENV PYTHONUNBUFFERED 1
ENV VENV "/venv"
ENV PATH "${VENV}/bin:$PATH"
ENV PYTHONPATH "${PYTHONPATH}:/src"

WORKDIR /src

COPY ./src /src
COPY pyproject.toml README.md ./

RUN apt-get update && apt-get install -y gcc libffi-dev g++
RUN pip install "poetry"
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

CMD python app